CREATE TABLE Function(
   function_code  INTEGER  NOT NULL PRIMARY KEY 
  ,function       VARCHAR(38) NOT NULL
  ,function_group VARCHAR(22) NOT NULL
);
INSERT INTO Function(function_code,function,function_group) VALUES (25,'Lawyer','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (202,'Tax and Accounting Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (109,'Senior Payroll Department Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (229,'Engineering Analyst','Engineering');
INSERT INTO Function(function_code,function,function_group) VALUES (238,'Financial Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (200,'Legal Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (13,'Engineering Assistant','Engineering');
INSERT INTO Function(function_code,function,function_group) VALUES (213,'Accounting and Tax Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (111,'Administrative Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (64,'Accounting Assistant I','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (43,'Payroll Department Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (57,'Legal Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (75,'Maintenance Assistant','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (217,'Accounting and Tax Clerk','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (84,'Purchaser','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (237,'Safety and Environmental Coordinator','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (124,'Payroll Department Manager','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (207,'Administrative Manager','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (29,'Civil Engineer','Engineering');
INSERT INTO Function(function_code,function,function_group) VALUES (203,'Accounting Manager','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (35,'Payroll Department Manager','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (224,'Strategies Manager','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (34,'Asset Manager','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (36,'Financial Manager','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (11,'Young Apprentice','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (78,'Mechanic','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (8,'Driver','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (116,'Cashier','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (2,'Bricklayer','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (231,'Bricklayer B','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (236,'Painter B','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (21,'Receptionist','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (1,'Servant','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (104,'Director','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (20,'Trainee','Trainees');
INSERT INTO Function(function_code,function,function_group) VALUES (105,'General Services','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (10,'Watchman','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (225,'Administrative Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (113,'Mechanical Assistant','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (232,'Carpenter B','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (18,'Assembler','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (208,'Sales Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (51,'Marketing Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (205,'Senior Legal Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (39,'Administrative Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (15,'Collection Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (7,'General Services Assistant','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (85,'Collection Coordinator','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (32,'Portfolio Manager','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (234,'SDR','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (245,'Customer Service Supervisor','Managers');
INSERT INTO Function(function_code,function,function_group) VALUES (4,'Painter','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (3,'Carpenter','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (44,'Construction Manager','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (12,'Storekeeper','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (5,'Iron Worker B','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (204,'Office Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (96,'Construction Foreman','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (101,'Tower Crane Operator','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (6,'Concrete Mixer Operator','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (223,'Machine Operator','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (27,'Safety Technician','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (219,'Engineering Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (221,'Tiler','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (107,'Foreman','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (226,'Plasterer','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (98,'Construction Foreman II','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (233,'Bricklayer A','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (235,'Painter A','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (123,'Warehouse Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (102,'Gantry Crane Operator','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (230,'Doorman','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (222,'Grout Applicator','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (120,'Locksmith','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (117,'Signaler','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (228,'Foreman I','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (214,'Foreman II','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (215,'Foreman III','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (112,'Junior Construction Worker','Assistants');
INSERT INTO Function(function_code,function,function_group) VALUES (97,'Construction Foreman I','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (218,'Mini Crane Operator','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (210,'File Clerk','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (239,'Payroll Department Coordinator','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (108,'Foreman I','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (211,'Junior Payroll Department Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (110,'Financial Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (243,'Purchasing Department Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (246,'Iron Worker A','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (17,'Electrician','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (240,'Plumber','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (241,'Reinforcement Foreman','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (242,'Waterproofing Technician','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (244,'Controller Analyst','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (100,'Backhoe Operator','Machine Operators');
INSERT INTO Function(function_code,function,function_group) VALUES (247,'Tile Layer','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (122,'Coating Grout Applicator','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (250,'Asset and Warehouse Manager','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (249,'Reinforcement Worker','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (253,'Junior Administrative Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (251,'Junior Purchasing Department Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (248,'Carpenter A','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (252,'Safety Technician Assistant','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (255,'SSMA Coordinator','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (257,'General Foreman','Production Supervisors');
INSERT INTO Function(function_code,function,function_group) VALUES (254,'Electrician A','Professionals');
INSERT INTO Function(function_code,function,function_group) VALUES (256,'Safety Technician B','Administration');
INSERT INTO Function(function_code,function,function_group) VALUES (258,'Safety Technician Assistant','Administration');
